
#World Generation settings
[worldgen]
	#Generation of Krypton Glowstone in nether
	krypton_gen = true
	#Generation of Neon Glowstone in nether
	neon_gen = true
	#Generation of Argon Glowstone in nether
	argon_gen = true

