
#Configuration options to handle the spawning of the Merpig
[spawning]
	#Biomes to spawn the Merpig inside
	spawn_biomes = ["minecraft:cold_ocean", "minecraft:frozen_ocean", "minecraft:lukewarm_ocean", "minecraft:ocean", "minecraft:warm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_ocean", "minecraft:deep_warm_ocean"]
	#Smallest number to spawn in a group.
	#Range: > 0
	spawn_group_min = 2
	#Should the merpig spawn in the world
	should_spawn = true
	#Largest number to spawn in a group.
	#Range: > 0
	spawn_group_max = 5
	#How likely the entity is to spawn, 10 is the same as squid. The higher the value the higher the spawn chance
	#Range: > 0
	spawn_weight = 10

