
[oregen]
	#Chance for a Black Opal Ore vein to spawn in a chunk. Default = 0.0725
	#Range: 0.0 ~ 1.0
	black_opal_chance = 0.0725
	#Maximum vein size for an Amethyst Ore vein. For reference, diamonds have a max vein size of 8. Default = 7
	#Range: 0 ~ 64
	amethyst_max_vein_size = 7
	#Chance for an Amethyst Ore vein to spawn in a chunk. 1.00 = As common as diamonds, 0.50 = Around half as common as diamonds etc. Default = 0.2875
	#Range: 0.0 ~ 1.0
	amethyst_chance = 0.2875
	#Maximum vein size for an Black Opal Ore vein. Default = 6
	#Range: 0 ~ 64
	black_opal_max_vein_size = 6

[toolvalues]
	#Durability of the Black Opal Tool Set. Set to -1 for infinite durability. Default = -1
	#Range: -1 ~ 999999
	black_opal_durability = -1
	#Durability of the Amethyst Tool Set. For reference, the Diamond Tool Set has 1561 durability. Set to -1 for infinite durability. Default = 5500
	#Range: 0 ~ 999999
	amethyst_durability = 5500
	#Efficiency of the Black Opal Tool Set. Default = 16
	#Range: 0 ~ 64
	black_opal_efficiency = 16
	#Base Attack Damage of the Amethyst Tool Set. For reference, the Diamond Tool Set has 3 base attack damage. Default = 4
	#Range: 0 ~ 16
	amethyst_ad = 4
	#Base Attack Damage of the Black Opal Tool Set. Default = 5
	#Range: 0 ~ 16
	black_opal_ad = 5
	#Efficiency of the Amethyst Tool Set. For reference, the Diamond Tool Set has 8 efficiency. Default = 12
	#Range: 0 ~ 64
	amethyst_efficiency = 12

[enchant]
	#Black Opal Enchantability. Default = 15
	#Range: 0 ~ 256
	black_opal = 15
	#Amethyst Enchantability. A higher value makes it easier to obtain higher level enchantments for less experience. For reference, diamonds have an enchantability of 10 and gold has an enchantability of 25. Default = 35
	#Range: 0 ~ 256
	amethyst = 35

[armorvalues]
	#Amethyst Chestplate Armor Value. Default = 8
	#Range: 0 ~ 16
	amethyst_chestplate_armor = 8
	#Amethyst Leggings Armor Value. Default = 7
	#Range: 0 ~ 16
	amethyst_leggings_armor = 7
	#Average Durability for the Amethyst Armor Set. Set -1 for infinite durability. Default = -1
	#Range: 0 ~ 99999999
	black_opal_armor_durability = 0
	#Black Opal Boots Armor Value. Default = 3
	#Range: 0 ~ 8
	black_opal_boots_armor = 3
	#Amethyst Helmet Armor Value. Indicates how many half-armor points the indicated armor will give. Default = 3
	#Range: 0 ~ 8
	amethyst_helmet_armor = 3
	#Amethyst Boots Armor Value. Default = 3
	#Range: 0 ~ 8
	amethyst_boots_armor = 3
	#Toughness for the Black Opal Armor Set. Default = 6
	#Range: 0 ~ 16
	black_opal_armor_toughness = 6
	#Base Durability for the Amethyst Armor Set. For reference, Diamond Armor has 33 base durability. Set -1 for infinite durability. Default = 132
	#Range: 0 ~ 99999999
	amethyst_armor_durability = 132
	#Black Opal Chestplate Armor Value. Default = 9
	#Range: 0 ~ 16
	black_opal_chestplate_armor = 9
	#Black Opal Leggings Armor Value. Default = 7
	#Range: 0 ~ 16
	black_opal_leggings_armor = 7
	#Toughness for the Amethyst Armor Set. Toughness reduces the armor penetration of high damaging attacks. Default = 4
	#Range: 0 ~ 16
	amethyst_armor_toughness = 4
	#Black Opal Helmet Armor Value. Default = 3
	#Range: 0 ~ 8
	black_opal_helmet_armor = 3

